### ISSUE TITLE
Failed to register commands on Velocity 3.0

### ISSUE THREAD

**Issue by MTM123** [MTM123/AuthMeVelocity#1]
`Couldn't pass ProxyInitializeEvent to authmevelocity
java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandManager.register(com.velocitypowered.api.command.Command, java.lang.String[])'
        at fr.xephi.authmevelocity.AuthMeVelocity.onInit(AuthMeVelocity.java:75) ~[?:?]
        at fr.xephi.authmevelocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity.jar:3.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by ghost** [comment]
any update on that?

**Comment by MTM123** [comment]
Not yet but I will update it as soon as I can

**Comment by ghost** [comment]
Thanks for information!
I hope the fix will not be too hard to do.
